package vn.aptech.mail.Entities;
// Generated Oct 3, 2014 11:46:33 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attachs generated by hbm2java
 */
@Entity
@Table(name="Attachs"
    ,schema="dbo"
    ,catalog="MAIL_SERVER"
)
public class Attachs  implements java.io.Serializable {


     private int attachId;
     private Mail mail;
     private String attachName;

    public Attachs() {
    }

	
    public Attachs(int attachId, String attachName) {
        this.attachId = attachId;
        this.attachName = attachName;
    }
    public Attachs(int attachId, Mail mail, String attachName) {
       this.attachId = attachId;
       this.mail = mail;
       this.attachName = attachName;
    }
   
     @Id 

    
    @Column(name="AttachId", unique=true, nullable=false)
    public int getAttachId() {
        return this.attachId;
    }
    
    public void setAttachId(int attachId) {
        this.attachId = attachId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MailId")
    public Mail getMail() {
        return this.mail;
    }
    
    public void setMail(Mail mail) {
        this.mail = mail;
    }

    
    @Column(name="AttachName", nullable=false, length=60)
    public String getAttachName() {
        return this.attachName;
    }
    
    public void setAttachName(String attachName) {
        this.attachName = attachName;
    }




}


