package vn.aptech.mail.Entities;
// Generated Oct 13, 2014 3:31:18 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mail generated by hbm2java
 */
@Entity
@Table(name="Mail"
    ,schema="dbo"
    ,catalog="MAIL_SERVER"
)
public class Mail  implements java.io.Serializable {


     private int mailId;
     private Users usersByAccountSendId;
     private Users usersByAccountReceiveId;
     private String cc;
     private String title;
     private String content;
     private Date sendDate;
     private boolean status;
     private Set<Attachs> attachses = new HashSet<Attachs>(0);

    public Mail() {
    	usersByAccountSendId=new Users();
    	usersByAccountReceiveId=new Users();
    }

	
    public Mail(int mailId, Users usersByAccountSendId, Users usersByAccountReceiveId, String title, String content, Date sendDate, boolean status) {
        this.mailId = mailId;
        this.usersByAccountSendId = usersByAccountSendId;
        this.usersByAccountReceiveId = usersByAccountReceiveId;
        this.title = title;
        this.content = content;
        this.sendDate = sendDate;
        this.status = status;
    }
    public Mail(int mailId, Users usersByAccountSendId, Users usersByAccountReceiveId, String cc, String title, String content, Date sendDate, Date readDate, boolean status, Set<Attachs> attachses) {
       this.mailId = mailId;
       this.usersByAccountSendId = usersByAccountSendId;
       this.usersByAccountReceiveId = usersByAccountReceiveId;
       this.cc = cc;
       this.title = title;
       this.content = content;
       this.sendDate = sendDate;
       this.status = status;
       this.attachses = attachses;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @Column(name="MailId", unique=true, nullable=false)
    public int getMailId() {
        return this.mailId;
    }
    
    public void setMailId(int mailId) {
        this.mailId = mailId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="AccountSendId", nullable=false)
    public Users getUsersByAccountSendId() {
        return this.usersByAccountSendId;
    }
    
    public void setUsersByAccountSendId(Users usersByAccountSendId) {
        this.usersByAccountSendId = usersByAccountSendId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="AccountReceiveId", nullable=false)
    public Users getUsersByAccountReceiveId() {
        return this.usersByAccountReceiveId;
    }
    
    public void setUsersByAccountReceiveId(Users usersByAccountReceiveId) {
        this.usersByAccountReceiveId = usersByAccountReceiveId;
    }

    
    @Column(name="Cc", length=60)
    public String getCc() {
        return this.cc;
    }
    
    public void setCc(String cc) {
        this.cc = cc;
    }

    
    @Column(name="Title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="Content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SendDate", nullable=false, length=23)
    public Date getSendDate() {
        return this.sendDate;
    }
    
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }


    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mail")
    public Set<Attachs> getAttachses() {
        return this.attachses;
    }
    
    public void setAttachses(Set<Attachs> attachses) {
        this.attachses = attachses;
    }




}


