package vn.aptech.mail.Entities;
// Generated Oct 3, 2014 11:46:33 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Profiles generated by hbm2java
 */
@Entity
@Table(name="Profiles"
    ,schema="dbo"
    ,catalog="MAIL_SERVER"
)
public class Profiles  implements Serializable {


     private String accountId;
     private Users users;
     private String fullName;
     private String address;
     private boolean gender;
     private String phone;
     private String picture;
     private String class_;

    public Profiles() {
    }

	
    public Profiles(Users users, String fullName, String address, boolean gender, String phone) {
        this.users = users;
        this.fullName = fullName;
        this.address = address;
        this.gender = gender;
        this.phone = phone;
    }
    public Profiles(Users users, String fullName, String address, boolean gender, String phone, String picture, String class_) {
       this.users = users;
       this.fullName = fullName;
       this.address = address;
       this.gender = gender;
       this.phone = phone;
       this.picture = picture;
       this.class_ = class_;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="users"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="AccountId", unique=true, nullable=false)
    public String getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="FullName", nullable=false)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="Address", nullable=false)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Gender", nullable=false)
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }

    
    @Column(name="Phone", nullable=false, length=13)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Picture", length=60)
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }

    
    @Column(name="Class")
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }




}


